version: "3.3"

services:

  postgres:
    build: ./postgres/
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: db_user
      POSTGRES_DB: postgres

  redis:
    image: redis:alpine3.8
    restart: always
    volumes:
      - redis_data:/data:rw
    ports:
      - 6379:6379

  flask_template:
    build: ../flask_template/
    volumes:
      - ../flask_template:/app:rw
      - pip_flask_template:/pip-cache:rw
    ports:
      - 8080:8080
    environment:
      ENV: development
      GUNICORN_WORKERS: 1
      GUNICORN_RELOAD: 1
      GUNICORN_BIND: 0.0.0.0:8080
      SKIP_PIP: ${skip_pip}


volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pip_flask_template:
    driver: local
